version: '3.1'
services:
  db:
    image: docker.io/library/postgres:15.5
    restart: always
    env_file:
      - .env
    volumes:
      - ./dataset:/docker-entrypoint-initdb.d
    ports:
      - 7777:5432
